name: Trigger Website Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Use github-scripts
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const activeWorkflows = await github.rest.actions.listWorkflowRuns({
                    owner: '${{ vars.WEBSITE_OWNER }}',
                    repo: '${{ vars.WEBSITE_REPO }}',
                    workflow_id: 'static.yml',
                    status: 'in_progress'
                });

                if (activeWorkflows?.data) {
                    for (const run of activeWorkflows.data['workflow_runs']) {
                        await github.rest.actions.cancelWorkflowRun({
                            owner: '${{ vars.WEBSITE_OWNER }}',
                            repo: '${{ vars.WEBSITE_REPO }}',
                            run_id: run.id,
                          });
                    }
                }

                await github.rest.actions.createWorkflowDispatch({
                owner: '${{ vars.WEBSITE_OWNER }}',
                repo: '${{ vars.WEBSITE_REPO }}',
                workflow_id: 'static.yml',
                ref: 'main',
                })
